jobs:
  fastbuild:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Cache local maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/accumulo

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Check for unapproved characters
      run: src/build/ci/find-unapproved-chars.sh
    - continue-on-error: true
      name: Check for unapproved JUnit API usage
      run: src/build/ci/find-unapproved-junit.sh
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Djansi.force=true
      name: Build with Maven (Fast Build)
      run: mvn -B -V -e -ntp "-Dstyle.color=always" clean package dependency:resolve
        -DskipTests -DskipFormat -DverifyFormat
      timeout-minutes: 20
  mvn:
    needs: fastbuild
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.profile.javaver }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.profile.javaver }}
    - continue-on-error: true
      name: Cache local maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/accumulo

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Override DNS to fix IP address for hostname
      run: "ip -br addr\necho \"'hostname -i' shows '$(hostname -i)'\"\necho \"'hostname\
        \ -I' shows '$(hostname -I)'\"\nhostname_short=$(hostname -s)\nhostname_long=$(hostname\
        \ -f)\nif ! grep -q $hostname_short /etc/hosts; then\n  actual_ip=$(ip -4\
        \ addr show dev eth0 | grep -o 'inet [0-9.]*' | cut -f2 -d ' ')\n  echo \"\
        Setting $hostname_long / $hostname_short to $actual_ip in /etc/hosts\"\n \
        \ echo \"$actual_ip $hostname_long $hostname_short\" | sudo tee -a /etc/hosts\n\
        \  ip -br addr\n  echo \"'hostname -i' shows '$(hostname -i)'\"\n  echo \"\
        'hostname -I' shows '$(hostname -I)'\"\nfi\n"
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Djansi.force=true
      name: Build with Maven (${{ matrix.profile.name }})
      run: mvn -B -V -e -ntp "-Dstyle.color=always" -DskipFormat ${{ matrix.profile.args
        }}
      timeout-minutes: 60
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload unit test results
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: surefire-reports-${{ matrix.profile.name }}
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload integration test results
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: failsafe-reports-${{ matrix.profile.name }}
        path: ./**/target/failsafe-reports/
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload mini test logs
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: ignore
        name: mini-tests-logs-${{ matrix.profile.name }}
        path: ./**/target/**/mini-tests/**/logs/
    strategy:
      fail-fast: false
      matrix:
        profile:
        - args: verify -PskipQA -DskipTests=false
          javaver: 17
          name: unit-tests
        - args: verify javadoc:jar -Psec-bugs -DskipTests -Dspotbugs.timeout=3600000
          javaver: 17
          name: qa-checks
        - args: package -DskipTests -Dversion.hadoop=3.0.3 -Dversion.zookeeper=3.5.10
          javaver: 17
          name: compat
        - args: verify -Perrorprone,skipQA
          javaver: 17
          name: errorprone
name: QA
on:
  repository_dispatch:
    types: trigger-ga___maven.yaml
permissions:
  contents: read
