jobs:
  shellcheck:
    name: ShellCheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Install shfmt
      run: src/build/ci/install-shfmt.sh
    - continue-on-error: true
      name: Running shellcheck on all scripts
      run: src/build/ci/run-shellcheck.sh
    timeout-minutes: 3
  shfmt:
    name: shfmt
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Install shfmt
      run: src/build/ci/install-shfmt.sh
    - continue-on-error: true
      name: Checking formatting of all scripts
      run: src/build/ci/run-shfmt.sh
    timeout-minutes: 3
  thrift:
    name: Thrift
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Update package repository
      run: sudo apt-get update
    - continue-on-error: true
      name: Install xmllint
      run: sudo apt-get install libxml2-utils
    - continue-on-error: true
      name: Install thrift
      run: src/build/ci/install-thrift.sh
    - continue-on-error: true
      name: Running thrift to check for changes
      run: src/build/ci/run-thrift.sh
    timeout-minutes: 3
name: ScriptQA
on:
  repository_dispatch:
    types: trigger-ga___scripts.yaml
permissions:
  contents: read
